return {
  name = "ZOMBIE",
  sprite = 'zumbi',
  path = 'enemies.zombie',
  power = 40,
  cost = 3,
  dir = new(Vec) {-1,0},
  delay = 2,
  movement = true,
  hitbox = new(Box) {-20, 20, -20, 20},
  description = ":(",
  group = 'enemies',
  speed = 25,
  max_hp = 100,
}
